services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  productnotifier:
    image: quintenps/productnotifier
    build:
      context: .
      dockerfile: Dockerfile